# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class AllocineMoviescraperItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    id_movie = scrapy.Field()
    title = scrapy.Field()
    original_title = scrapy.Field()
    press_rating = scrapy.Field()
    audience_rating = scrapy.Field()
    gender = scrapy.Field()
    year = scrapy.Field()
    duration = scrapy.Field()
    description = scrapy.Field()
    main_actors = scrapy.Field()
    id_person = scrapy.Field() 
    role = scrapy.Field()
    name = scrapy.Field()
    birth_name = scrapy.Field()
    nationality = scrapy.Field()
    birth_date = scrapy.Field()
    total_roles = scrapy.Field()
    nominations = scrapy.Field()
    biographie = scrapy.Field()
    all_actors = scrapy.Field()
    director = scrapy.Field()
    writer = scrapy.Field()
    public = scrapy.Field()
    country = scrapy.Field()
    language = scrapy.Field()
    box_office = scrapy.Field()
    budget = scrapy.Field()
    devise = scrapy.Field()
    url = scrapy.Field()

class AllocineSeriescraperItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    id_serie = scrapy.Field()
    title = scrapy.Field()
    original_title = scrapy.Field()
    global_press_rating = scrapy.Field()
    global_audience_rating = scrapy.Field()
    gender = scrapy.Field()
    start_year = scrapy.Field()
    end_year = scrapy.Field()
    duration = scrapy.Field()
    serie_description = scrapy.Field()
    creator = scrapy.Field()
    country = scrapy.Field()
    seasons_total = scrapy.Field()
    episodes_total = scrapy.Field()
    main_actors = scrapy.Field()
    url = scrapy.Field()
    season_synopsis = scrapy.Field()
    season_audience_rating = scrapy.Field()
    episode_code = scrapy.Field()
    episode_title = scrapy.Field()
    episode_resume = scrapy.Field()
    channel = scrapy.Field()
    id_person = scrapy.Field()
    role = scrapy.Field()
    name = scrapy.Field()
    birth_name = scrapy.Field()
    total_roles = scrapy.Field()
    nominations = scrapy.Field()
    biographie = scrapy.Field()
    all_actors = scrapy.Field()    
    directors = scrapy.Field()
    writers = scrapy.Field() 